services:
  indexer:
    image: ghcr.io/otim-xyz/infra-sandbox/executor:main
    volumes:
      - /run/systemd/journal/socket:/run/systemd/journal/socket
    platform: linux/amd64
    pull_policy: always
    restart: unless-stopped
    environment:
      - OTIM_SYSLOG_IDENTIFIER=$OTIM_SYSLOG_IDENTIFIER
      - OTIM_DOCUMENTDB_URL=$OTIM_DOCUMENTDB_URL
      - OTIM_RPC_URL=$OTIM_RPC_URL
      - OTIM_FIBONACCI_ADDRESS=$OTIM_FIBONACCI_ADDRESS
      - OTIM_POLL_INTERVAL=$OTIM_POLL_INTERVAL
