services:
  anvil:
    image: ghcr.io/otim-xyz/infra-sandbox/chain:main
    platform: linux/amd64
    ports:
      - "8545:8545"
    pull_policy: always
    restart: unless-stopped

  deploy:
    image: ghcr.io/otim-xyz/infra-sandbox/contracts:main
    platform: linux/amd64
    pull_policy: always
    restart: no
    depends_on:
      - anvil
