name: docker

on: [push]

jobs:
  docker-base:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - dockerfile: ./agents/executor/Dockerfile
            context: ./agents
            image-name: agents
          - dockerfile: ./agents/indexer/Dockerfile
            context: ./agents
            image-name: agents
          - dockerfile: ./contracts/Dockerfile
            context: ./contracts
            image-name: contracts

    uses: ./.github/workflows/docker-base.yml
    with:
      dockerfile: ${{ matrix.settings.dockerfile }}
      context: ${{ matrix.settings.context }}
      image-name: ${{ matrix.settings.image-name }}
